### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by TravelTrader** [barrycahill/Python-iPhone-Motion-sensor#1]
Do I understand right, that I can catch the sensor data of my iPhone on my laptop with your code?
Please, can you give any examples how to really use it. Would be very interesting!

**Comment by ghost** [comment]
Yes, you understand correctly.
Using an app on the iPhone (called 'Sensor Streamer' which streams the sensor data over UDP, but unfortunately it no longer works under iOS12+), this code can receive it on the laptop.
If you need to do something like that now, you could look into some of the other apps that do something similar (like https://apps.apple.com/us/app/sensor-data/id397619802), but personally, I haven't used this in the past few years (since the initial app stopped being supported on iOS)

**Comment by TravelTrader** [comment]
> I did not find an iOS App called "Sensor Streamer".
> My system is updated to the newest iOS version. I only found "Sensor Logger - Stream sensor data" ... but that's not the one you mentioned, right?

**Update:** Is this the right app:
https://apps.apple.com/us/app/sensor-data-streamer/id608278214

It would be so great to have such a possibility! Thanks for helping me!
